"""Add age column to users

Revision ID: 7bf3072daa7f
Revises: ca339e02cb11
Create Date: 2026-06-08 21:53:59.198166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf3072daa7f'
down_revision: Union[str, Sequence[str], None] = 'ca339e02cb11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('All_users', sa.Column('age', sa.Integer(), nullable=True))
    """Also we can change here a name of the table:"""
    op.alter_column('All_users','client_name',new_column_name='username',existing_type=sa.String())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('All_users', 'age')
    # ### end Alembic commands ###
