"""rename_column

Revision ID: 8bf5661f6a77
Revises: fb284da87a97
Create Date: 2026-06-09 23:14:09.367296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf5661f6a77'
down_revision: Union[str, Sequence[str], None] = 'fb284da87a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aiconfig_table','monthly_budget_usd',new_column_name='budget',existing_type=sa.Float)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
